service: start-war

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  timeout: 15

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'
    environment:
      STAGE: prod
      SYNCRONIZE: false
      MYSQL_SERVICE: mysql
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: starwar
      BACKEND_PORT: 3000
      SWAPI_URL: https://swapi.py4e.com/api

plugins:
  - serverless-jetpack
  - serverless-offline
